#a git hub action to deploy to repository 'releases' sections
name: PrefixTreeStorage - deploy release
run-name: Deploying a release
on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs: 
  prepare-release:
    name: Deploy release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          #check if sudo is installed
          if ! [ -x "$(command -v sudo)" ]; then
            echo "sudo is not installed. Installing sudo..."
            apt update -y > /dev/null 2>&1
            apt install sudo -y
            sudo apt update -y
          fi
          sudo apt update -y
          sudo apt install -y make llvm clang git libssl-dev

      - name: Running tests
        run: |
          export TERM=xterm
          currFolder=$(pwd)
          git submodule update --init --recursive
          echo "Running tests..."
          cd tests
          make all
          cd build
          ./tests
          cd $currFolder

      - name: Building ...
        run: |
          export TERM=xterm
          backFolder=$(pwd)
          git submodule update --init --recursive

          echo "Building library..."

          cd library
          rm -rf build
          make all
          cd $backFolder

          #echo "Building command line tool ..."
          #cd command
          #rm -rf build
          #make all
          #cd $backFolder
          echo "Command doest not have a build step, because it is already compiled by tests (in the previous step)"


      - name: saving files to a tar.gz
        #run tar -czf, excluding .git and .github folders
        run: |
          currentFolderName=${PWD##*/}
          currFolder=$(pwd)
          deployFolderName="PrefixTreeStorage-${{ github.ref_name }}"
          destinationFileName="PrefixTreeStorage-${{ github.ref_name }}.tar.gz "

          cd ..
          
          mkdir -p $deployFolderName
          echo ============= Removind objects files =================
          rm -rf "$currentFolderName/command/build/objects"
          rm -rf "$currentFolderName/library/build/objects"
        
          echo ============= Copyng built files =================
          ls -lha "$currentFolderName/command"
          cp -r "$currentFolderName/command/build" "$deployFolderName/"
          mv "$deployFolderName/build" "$deployFolderName/command"

          ls -lha "$currentFolderName/library"
          cp -r "$currentFolderName/library/build" "$deployFolderName/"
          mv "$deployFolderName/build" "$deployFolderName/library"

          cp "$currentFolderName/CHANGELOG.md" "$deployFolderName/"

          echo "============= Packing the folder $deployFolderName $destinationFileName file ============="
          tar -czf $destinationFileName $deployFolderName
          
          mv $destinationFileName $currFolder/
          cd $currFolder
          echo ============= final folder content =================
          ls -lha

      - name: Create Release
        id: create_release2
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          bodyFile: CHANGELOG.md
          artifacts: PrefixTreeStorage-${{ github.ref_name }}.tar.gz
          artifactContentType: application/x-gzip
